/* part of the hp/mp integer overflow fix */
ALTER TABLE `player`
MODIFY COLUMN `hp`  int NOT NULL DEFAULT 0 AFTER `exit_map_index`,
MODIFY COLUMN `mp`  int NOT NULL DEFAULT 0 AFTER `hp`;

/* update old mob_proto table */
ALTER TABLE `mob_proto`
MODIFY COLUMN `setRaceFlag`  set('ANIMAL','UNDEAD','DEVIL','HUMAN','ORC','MILGYO','INSECT','FIRE','ICE','DESERT','TREE','ATT_ELEC','ATT_FIRE','ATT_ICE','ATT_WIND','ATT_EARTH','ATT_DARK') NOT NULL DEFAULT '' AFTER `mount_capacity`,
MODIFY COLUMN `setImmuneFlag`  set('STUN','SLOW','FALL','CURSE','POISON','TERROR','REFLECT') NOT NULL DEFAULT '' AFTER `setRaceFlag`;

/* add belt_inventory if missing */
ALTER TABLE `item`
MODIFY COLUMN `window`  enum('INVENTORY','EQUIPMENT','SAFEBOX','MALL','DRAGON_SOUL_INVENTORY','BELT_INVENTORY','GROUND') NOT NULL DEFAULT 'INVENTORY' AFTER `owner_id`;

/* new 40k game bonuses 1-5 */
ALTER TABLE `item_attr`
MODIFY COLUMN `apply`  enum('MAX_HP','MAX_SP','CON','INT','STR','DEX','ATT_SPEED','MOV_SPEED','CAST_SPEED','HP_REGEN','SP_REGEN','POISON_PCT','STUN_PCT','SLOW_PCT','CRITICAL_PCT','PENETRATE_PCT','ATTBONUS_HUMAN','ATTBONUS_ANIMAL','ATTBONUS_ORC','ATTBONUS_MILGYO','ATTBONUS_UNDEAD','ATTBONUS_DEVIL','STEAL_HP','STEAL_SP','MANA_BURN_PCT','DAMAGE_SP_RECOVER','BLOCK','DODGE','RESIST_SWORD','RESIST_TWOHAND','RESIST_DAGGER','RESIST_BELL','RESIST_FAN','RESIST_BOW','RESIST_FIRE','RESIST_ELEC','RESIST_MAGIC','RESIST_WIND','REFLECT_MELEE','REFLECT_CURSE','POISON_REDUCE','KILL_SP_RECOVER','EXP_DOUBLE_BONUS','GOLD_DOUBLE_BONUS','ITEM_DROP_BONUS','POTION_BONUS','KILL_HP_RECOVER','IMMUNE_STUN','IMMUNE_SLOW','IMMUNE_FALL','SKILL','BOW_DISTANCE','ATT_GRADE_BONUS','DEF_GRADE_BONUS','MAGIC_ATT_GRADE_BONUS','MAGIC_DEF_GRADE_BONUS','CURSE_PCT','MAX_STAMINA','ATT_BONUS_TO_WARRIOR','ATT_BONUS_TO_ASSASSIN','ATT_BONUS_TO_SURA','ATT_BONUS_TO_SHAMAN','ATT_BONUS_TO_MONSTER','ATT_BONUS','MALL_DEFBONUS','MALL_EXPBONUS','MALL_ITEMBONUS','MALL_GOLDBONUS','MAX_HP_PCT','MAX_SP_PCT','SKILL_DAMAGE_BONUS','NORMAL_HIT_DAMAGE_BONUS','SKILL_DEFEND_BONUS','NORMAL_HIT_DEFEND_BONUS','PC_BANG_EXP_BONUS','PC_BANG_DROP_BONUS','EXTRACT_HP_PCT','RESIST_WARRIOR','RESIST_ASSASSIN','RESIST_SURA','RESIST_SHAMAN','ENERGY','DEF_GRADE','COSTUME_ATTR_BONUS','MAGIC_ATT_BONUS_PER','MELEE_MAGIC_ATT_BONUS_PER','RESIST_ICE','RESIST_EARTH','RESIST_DARK','RESIST_CRITICAL','RESIST_PENETRATE','BLEEDING_REDUCE', 'BLEEDING_PCT', 'ATT_BONUS_TO_WOLFMAN', 'RESIST_WOLFMAN', 'RESIST_CLAW') NOT NULL DEFAULT 'MAX_HP' FIRST ;

/* new 40k game bonuses 6-7 */
ALTER TABLE `item_attr_rare`
MODIFY COLUMN `apply`  enum('MAX_HP','MAX_SP','CON','INT','STR','DEX','ATT_SPEED','MOV_SPEED','CAST_SPEED','HP_REGEN','SP_REGEN','POISON_PCT','STUN_PCT','SLOW_PCT','CRITICAL_PCT','PENETRATE_PCT','ATTBONUS_HUMAN','ATTBONUS_ANIMAL','ATTBONUS_ORC','ATTBONUS_MILGYO','ATTBONUS_UNDEAD','ATTBONUS_DEVIL','STEAL_HP','STEAL_SP','MANA_BURN_PCT','DAMAGE_SP_RECOVER','BLOCK','DODGE','RESIST_SWORD','RESIST_TWOHAND','RESIST_DAGGER','RESIST_BELL','RESIST_FAN','RESIST_BOW','RESIST_FIRE','RESIST_ELEC','RESIST_MAGIC','RESIST_WIND','REFLECT_MELEE','REFLECT_CURSE','POISON_REDUCE','KILL_SP_RECOVER','EXP_DOUBLE_BONUS','GOLD_DOUBLE_BONUS','ITEM_DROP_BONUS','POTION_BONUS','KILL_HP_RECOVER','IMMUNE_STUN','IMMUNE_SLOW','IMMUNE_FALL','SKILL','BOW_DISTANCE','ATT_GRADE_BONUS','DEF_GRADE_BONUS','MAGIC_ATT_GRADE_BONUS','MAGIC_DEF_GRADE_BONUS','CURSE_PCT','MAX_STAMINA','ATT_BONUS_TO_WARRIOR','ATT_BONUS_TO_ASSASSIN','ATT_BONUS_TO_SURA','ATT_BONUS_TO_SHAMAN','ATT_BONUS_TO_MONSTER','ATT_BONUS','MALL_DEFBONUS','MALL_EXPBONUS','MALL_ITEMBONUS','MALL_GOLDBONUS','MAX_HP_PCT','MAX_SP_PCT','SKILL_DAMAGE_BONUS','NORMAL_HIT_DAMAGE_BONUS','SKILL_DEFEND_BONUS','NORMAL_HIT_DEFEND_BONUS','PC_BANG_EXP_BONUS','PC_BANG_DROP_BONUS','EXTRACT_HP_PCT','RESIST_WARRIOR','RESIST_ASSASSIN','RESIST_SURA','RESIST_SHAMAN','ENERGY','DEF_GRADE','COSTUME_ATTR_BONUS','MAGIC_ATT_BONUS_PER','MELEE_MAGIC_ATT_BONUS_PER','RESIST_ICE','RESIST_EARTH','RESIST_DARK','RESIST_CRITICAL','RESIST_PENETRATE','BLEEDING_REDUCE', 'BLEEDING_PCT', 'ATT_BONUS_TO_WOLFMAN', 'RESIST_WOLFMAN', 'RESIST_CLAW') NOT NULL DEFAULT 'MAX_HP' FIRST ;

/* 5 characters in the select phase */
ALTER TABLE `player_index`
ADD COLUMN `pid5`  int UNSIGNED NOT NULL DEFAULT 0 AFTER `pid4`,
ADD INDEX `pid5_key` USING BTREE (`pid5`) ;

/* new skill_proto way to handle skill points (backwards compatible) varchar->enum */
ALTER TABLE `skill_proto`
MODIFY COLUMN `szPointOn`  enum('NONE','MAX_HP','MAX_SP','HP_REGEN','SP_REGEN','BLOCK','HP','SP','ATT_GRADE','DEF_GRADE','MAGIC_ATT_GRADE','MAGIC_DEF_GRADE','BOW_DISTANCE','MOV_SPEED','ATT_SPEED','POISON_PCT','RESIST_RANGE','RESIST_MELEE','CASTING_SPEED','REFLECT_MELEE','ATT_BONUS','DEF_BONUS','RESIST_NORMAL','DODGE','KILL_HP_RECOVER','KILL_SP_RECOVER','HIT_HP_RECOVER','HIT_SP_RECOVER','CRITICAL','MANASHIELD','SKILL_DAMAGE_BONUS','NORMAL_HIT_DAMAGE_BONUS') NOT NULL DEFAULT 'NONE' AFTER `bLevelLimit`,
MODIFY COLUMN `szPointOn2`  enum('NONE','MAX_HP','MAX_SP','HP_REGEN','SP_REGEN','BLOCK','HP','SP','ATT_GRADE','DEF_GRADE','MAGIC_ATT_GRADE','MAGIC_DEF_GRADE','BOW_DISTANCE','MOV_SPEED','ATT_SPEED','POISON_PCT','RESIST_RANGE','RESIST_MELEE','CASTING_SPEED','REFLECT_MELEE','ATT_BONUS','DEF_BONUS','RESIST_NORMAL','DODGE','KILL_HP_RECOVER','KILL_SP_RECOVER','HIT_HP_RECOVER','HIT_SP_RECOVER','CRITICAL','MANASHIELD','SKILL_DAMAGE_BONUS','NORMAL_HIT_DAMAGE_BONUS') NOT NULL DEFAULT 'NONE' AFTER `setAffectFlag`;

/* new skill_proto flag values */
ALTER TABLE `skill_proto`
MODIFY COLUMN `setFlag`  set('ATTACK','USE_MELEE_DAMAGE','COMPUTE_ATTGRADE','SELFONLY','USE_MAGIC_DAMAGE','USE_HP_AS_COST','COMPUTE_MAGIC_DAMAGE','SPLASH','GIVE_PENALTY','USE_ARROW_DAMAGE','PENETRATE','IGNORE_TARGET_RATING','ATTACK_SLOW','ATTACK_STUN','HP_ABSORB','SP_ABSORB','ATTACK_FIRE_CONT','REMOVE_BAD_AFFECT','REMOVE_GOOD_AFFECT','CRUSH','ATTACK_POISON','TOGGLE','DISABLE_BY_POINT_UP','CRUSH_LONG','ATTACK_WIND','ATTACK_ELEC','ATTACK_FIRE','ATTACK_BLEEDING','PARTY') NULL DEFAULT NULL AFTER `szAttackGradePoly`,
MODIFY COLUMN `setAffectFlag`  enum('YMIR','INVISIBILITY','SPAWN','POISON','SLOW','STUN','DUNGEON_READY','DUNGEON_UNIQUE','BUILDING_CONSTRUCTION_SMALL','BUILDING_CONSTRUCTION_LARGE','BUILDING_UPGRADE','MOV_SPEED_POTION','ATT_SPEED_POTION','FISH_MIND','JEONGWIHON','GEOMGYEONG','CHEONGEUN','GYEONGGONG','EUNHYUNG','GWIGUM','TERROR','JUMAGAP','HOSIN','BOHO','KWAESOK','MANASHIELD','MUYEONG','REVIVE_INVISIBLE','FIRE','GICHEON','JEUNGRYEOK','TANHWAN_DASH','PABEOP','CHEONGEUN_WITH_FALL','POLYMORPH','WAR_FLAG1','WAR_FLAG2','WAR_FLAG3','CHINA_FIREWORK','HAIR','GERMANY','RAMADAN_RING','BLEEDING','RED_POSSESSION','BLUE_POSSESSION') NOT NULL DEFAULT 'YMIR' AFTER `setFlag`,
MODIFY COLUMN `setAffectFlag2`  enum('YMIR','INVISIBILITY','SPAWN','POISON','SLOW','STUN','DUNGEON_READY','DUNGEON_UNIQUE','BUILDING_CONSTRUCTION_SMALL','BUILDING_CONSTRUCTION_LARGE','BUILDING_UPGRADE','MOV_SPEED_POTION','ATT_SPEED_POTION','FISH_MIND','JEONGWIHON','GEOMGYEONG','CHEONGEUN','GYEONGGONG','EUNHYUNG','GWIGUM','TERROR','JUMAGAP','HOSIN','BOHO','KWAESOK','MANASHIELD','MUYEONG','REVIVE_INVISIBLE','FIRE','GICHEON','JEUNGRYEOK','TANHWAN_DASH','PABEOP','CHEONGEUN_WITH_FALL','POLYMORPH','WAR_FLAG1','WAR_FLAG2','WAR_FLAG3','CHINA_FIREWORK','HAIR','GERMANY','RAMADAN_RING','BLEEDING','RED_POSSESSION','BLUE_POSSESSION') NOT NULL DEFAULT 'YMIR' AFTER `szDurationPoly2`
;

/* new costume item attr fields */
ALTER TABLE `item_attr`
MODIFY COLUMN `prob`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `apply`,
MODIFY COLUMN `lv1`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `prob`,
MODIFY COLUMN `lv2`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv1`,
MODIFY COLUMN `lv3`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv2`,
MODIFY COLUMN `lv4`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv3`,
MODIFY COLUMN `lv5`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv4`,
MODIFY COLUMN `weapon`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv5`,
MODIFY COLUMN `body`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `weapon`,
MODIFY COLUMN `wrist`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `body`,
MODIFY COLUMN `foots`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `wrist`,
MODIFY COLUMN `neck`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `foots`,
MODIFY COLUMN `head`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `neck`,
MODIFY COLUMN `shield`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `head`,
MODIFY COLUMN `ear`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `shield`,
ADD COLUMN `costume_body`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `ear`,
ADD COLUMN `costume_hair`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `costume_body`,
ADD COLUMN `costume_weapon`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `costume_hair`;

ALTER TABLE `item_attr_rare`
MODIFY COLUMN `prob`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `apply`,
MODIFY COLUMN `lv1`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `prob`,
MODIFY COLUMN `lv2`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv1`,
MODIFY COLUMN `lv3`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv2`,
MODIFY COLUMN `lv4`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv3`,
MODIFY COLUMN `lv5`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv4`,
MODIFY COLUMN `weapon`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `lv5`,
MODIFY COLUMN `body`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `weapon`,
MODIFY COLUMN `wrist`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `body`,
MODIFY COLUMN `foots`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `wrist`,
MODIFY COLUMN `neck`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `foots`,
MODIFY COLUMN `head`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `neck`,
MODIFY COLUMN `shield`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `head`,
MODIFY COLUMN `ear`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `shield`,
ADD COLUMN `costume_body`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `ear`,
ADD COLUMN `costume_hair`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `costume_body`,
ADD COLUMN `costume_weapon`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `costume_hair`;





